FROM debian:stretch

ARG BUNDLE_DIR

RUN apt-get update -y \
  && apt-get install curl apt-transport-https lsb-release gnupg -y \
  && curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null \
  && AZ_REPO=$(lsb_release -cs) \
  && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list \
  && apt-get update \
  && apt-get install azure-cli

COPY . $BUNDLE_DIR
