// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.4
// source: pkg/sbom/plugins/proto/sbom_generator_protocol.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SBOMGeneratorProtocolClient is the client API for SBOMGeneratorProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SBOMGeneratorProtocolClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	Connect(ctx context.Context, in *SBOMConnectRequest, opts ...grpc.CallOption) (*SBOMConnectResponse, error)
}

type sBOMGeneratorProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewSBOMGeneratorProtocolClient(cc grpc.ClientConnInterface) SBOMGeneratorProtocolClient {
	return &sBOMGeneratorProtocolClient{cc}
}

func (c *sBOMGeneratorProtocolClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, "/plugins.SBOMGeneratorProtocol/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sBOMGeneratorProtocolClient) Connect(ctx context.Context, in *SBOMConnectRequest, opts ...grpc.CallOption) (*SBOMConnectResponse, error) {
	out := new(SBOMConnectResponse)
	err := c.cc.Invoke(ctx, "/plugins.SBOMGeneratorProtocol/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SBOMGeneratorProtocolServer is the server API for SBOMGeneratorProtocol service.
// All implementations must embed UnimplementedSBOMGeneratorProtocolServer
// for forward compatibility
type SBOMGeneratorProtocolServer interface {
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	Connect(context.Context, *SBOMConnectRequest) (*SBOMConnectResponse, error)
	mustEmbedUnimplementedSBOMGeneratorProtocolServer()
}

// UnimplementedSBOMGeneratorProtocolServer must be embedded to have forward compatible implementations.
type UnimplementedSBOMGeneratorProtocolServer struct {
}

func (UnimplementedSBOMGeneratorProtocolServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedSBOMGeneratorProtocolServer) Connect(context.Context, *SBOMConnectRequest) (*SBOMConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSBOMGeneratorProtocolServer) mustEmbedUnimplementedSBOMGeneratorProtocolServer() {}

// UnsafeSBOMGeneratorProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SBOMGeneratorProtocolServer will
// result in compilation errors.
type UnsafeSBOMGeneratorProtocolServer interface {
	mustEmbedUnimplementedSBOMGeneratorProtocolServer()
}

func RegisterSBOMGeneratorProtocolServer(s grpc.ServiceRegistrar, srv SBOMGeneratorProtocolServer) {
	s.RegisterService(&SBOMGeneratorProtocol_ServiceDesc, srv)
}

func _SBOMGeneratorProtocol_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SBOMGeneratorProtocolServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.SBOMGeneratorProtocol/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SBOMGeneratorProtocolServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SBOMGeneratorProtocol_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SBOMConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SBOMGeneratorProtocolServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.SBOMGeneratorProtocol/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SBOMGeneratorProtocolServer).Connect(ctx, req.(*SBOMConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SBOMGeneratorProtocol_ServiceDesc is the grpc.ServiceDesc for SBOMGeneratorProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SBOMGeneratorProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.SBOMGeneratorProtocol",
	HandlerType: (*SBOMGeneratorProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _SBOMGeneratorProtocol_Generate_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _SBOMGeneratorProtocol_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/sbom/plugins/proto/sbom_generator_protocol.proto",
}
