# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - "dependabot 🤖"
    schedule:
      interval: weekly
      day: sunday
    groups:
      go-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot 🤖"
    schedule:
      interval: weekly
      day: sunday
