tasks:
  - name: Runs docs server
    command:  |
              cd docs
              hugo server -D -F --noHTTPCache --baseUrl $(gp url 1313) --appendPort=false 
ports:
  - port: 1313
    visibility: private