FROM ubuntu:xenial

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates libssl-dev libffi-dev python3 python3-pip
RUN pip3 install sfctl

# Copy any scripts and local bundle files into the bundle
COPY . $BUNDLE_DIR
