// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: signing_protocol.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SigningProtocolClient is the client API for SigningProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SigningProtocolClient interface {
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type signingProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewSigningProtocolClient(cc grpc.ClientConnInterface) SigningProtocolClient {
	return &signingProtocolClient{cc}
}

func (c *signingProtocolClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/plugins.SigningProtocol/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingProtocolClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/plugins.SigningProtocol/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigningProtocolServer is the server API for SigningProtocol service.
// All implementations must embed UnimplementedSigningProtocolServer
// for forward compatibility
type SigningProtocolServer interface {
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedSigningProtocolServer()
}

// UnimplementedSigningProtocolServer must be embedded to have forward compatible implementations.
type UnimplementedSigningProtocolServer struct {
}

func (UnimplementedSigningProtocolServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedSigningProtocolServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedSigningProtocolServer) mustEmbedUnimplementedSigningProtocolServer() {}

// UnsafeSigningProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigningProtocolServer will
// result in compilation errors.
type UnsafeSigningProtocolServer interface {
	mustEmbedUnimplementedSigningProtocolServer()
}

func RegisterSigningProtocolServer(s grpc.ServiceRegistrar, srv SigningProtocolServer) {
	s.RegisterService(&SigningProtocol_ServiceDesc, srv)
}

func _SigningProtocol_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningProtocolServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.SigningProtocol/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningProtocolServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningProtocol_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningProtocolServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.SigningProtocol/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningProtocolServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SigningProtocol_ServiceDesc is the grpc.ServiceDesc for SigningProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigningProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.SigningProtocol",
	HandlerType: (*SigningProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _SigningProtocol_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _SigningProtocol_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signing_protocol.proto",
}
