// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "f2d332bc9137b8b7c14f02c6b2c70d99"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"806972cd3e2ff588560f62698b2f704d": "1f8b08000000000000ffb492318fdb300c8577fd8ad7786d92ebaaad43d13be08076e8a1e8484b4c2c9c2cba229de4fe7d213b29724bb77a92f91e9f3f93eaf063488aa4b08111a41cd271ae64490a0e52f15daa71751d7ec98c715643e4432a0c359e74b1308501145acb47f4b32d4995d55aaa4cad4ed975782941c6918b41ae26e5a54bd17396334c60f4ca38cc3983e2898ad19121079c07b22b0a021544f9e0dc982ea9a877c0167ce1e05ca1913d1ebf3c3f7f7327ae9aa4783cec3eed1e5c640d352d301e9bcf057ca171cafc37f5fecf372e959384e5fc34d2913da6c5b61d3867f1998cd59c4b458d725e11de7fe16995f0d81af0536a8e1b076021f5cb0968f3a0123d7ad2e15aa37a9cdb90f4666ad9db70f7c26190fb5ce7e6f20f92979bf8df58be8ac4fe8d6f345de4894be41212ab775df3ad9b19dff477bb090026aa34b2715d1ded8964d493f276359fa5c6a9b2aa735da81cb958a2fc3ef075ee79dddc2dd5068f7d15b1fdae89fbabfa270000ffff0e1065d3e7020000",
		"cc07845cb803077bd2ffe3d06cc005f8": "1f8b08000000000000ff64c9c10d80200c05d03b53d478c63f53213592486d0a35babd03787eeb82188ed214a237151e4792472aa12a17b019ecf2299e3d74b62ee4a194f79f6f2ff7337d010000ffff098e9c8a4f000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("templates", "./templates")
		b.SetResolver("porter.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "806972cd3e2ff588560f62698b2f704d"})
		b.SetResolver("run", packr.Pointer{ForwardBox: gk, ForwardPath: "cc07845cb803077bd2ffe3d06cc005f8"})
	}()

	return nil
}()
