// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "f2d332bc9137b8b7c14f02c6b2c70d99"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"806972cd3e2ff588560f62698b2f704d": "1f8b08000000000000ffac92316fdb3c108677fe8af7b3d6cf76ba6aeb50340102b44383a2e3893c5944289eca3bd9cebf2f28c9adb375a8268a7ceed1ab3b36f836444554d8c0f092fb789a0b59948c5e0abe4a312eaec10f9931ce6a08dcc7cc50e3491784c90f205f4bfe4737db622aac56ad32d57d4aaec14bf6328e9c0db241ca4b95a2e3241798c0e895d1cf2981c299b2d189213d2e03d916059e3282fce7dc18af316beb803df8cadeb94c23b778fcf4fcfcc59db96894dce2e1f0e1f0e002ab2f7109d362f73183af344e897f5befff7ce7623e8b5fd64f239db8c5b460fb8153923691b19a7331ab514a7f22d4557dde7fed69c5f0588bf15d4a0abb0dac1da11c5a74a4c3b647e534d736e9cd56ed7b7ff7c27e907b9b7373fecb2c2f37f01fa7f92c12ba37bee569024f9c03671f595bd7546e9dcef8a63feb6d003051a1918dcb4a2c61c9a823e5fd0a5fa484a9b0aa738d2f1c385ba4f45ef83a77bc4eef66b5a1c5b188d8f1500f8fdbe9af000000ffffdee41708eb020000",
		"cc07845cb803077bd2ffe3d06cc005f8": "1f8b08000000000000ff64c9c10d80200c05d03b53d478c63f53213592486d0a35babd03787eeb82188ed214a237151e4792472aa12a17b019ecf2299e3d74b62ee4a194f79f6f2ff7337d010000ffff098e9c8a4f000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("templates", "./templates")
		b.SetResolver("porter.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "806972cd3e2ff588560f62698b2f704d"})
		b.SetResolver("run", packr.Pointer{ForwardBox: gk, ForwardPath: "cc07845cb803077bd2ffe3d06cc005f8"})
	}()

	return nil
}()
