name: porter/porter-canary
on:
  workflow_dispatch:
    inputs:
      shouldPublish:
        description: Should Publish
        default: true
        type: boolean
        required: false
      skipTests:
        description: Skip Tests
        default: false
        type: boolean
        required: false
  push:
    branches:
      - main
      - release/*
jobs:
  build_pipelinesrelease_template_workflow_dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: build_pipelinesrelease_template
    uses: ./.github/workflows/build_pipelinesrelease_template.yml
    with:
      registry: ghcr.io/getporter
      shouldPublish: "${{inputs.shouldPublish}}"
      skipTests: "${{inputs.skipTests}}"
  build_pipelinesrelease_template_push:
    if: ${{ github.event_name == 'push' }}
    name: build_pipelinesrelease_template
    uses: ./.github/workflows/build_pipelinesrelease_template.yml
    with:
      registry: ghcr.io/getporter
      shouldPublish: true
      skipTests: false
