name: porter/porter-integration
# this will only run when this is on main branch apparently so use pr for now (temporary)
#on:
#  issue_comment:
#    types: [created, edited]
on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'docs/**'

env:
  GOVERSION: 1.20.7

jobs:
  Integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-go@v4
      with:
        go-version: "${{ env.GOVERSION }}"
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Native Build
      run: go run mage.go Build
      shell: bash
    - name: Integration Test
      run: go run mage.go -v TestIntegration
      shell: bash
