name: porter/porter-canary
on:
  workflow_dispatch:
    inputs:
      shouldPublish:
        default: true
        type: boolean
        required: false
      skipTests:
        default: false
        type: boolean
        required: false
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - split-builds
jobs:
  build_pipelinesrelease_template:
    name: build_pipelinesrelease_template
    uses: "./.github/workflows/build_pipelinesrelease_template.yml"
    with:
      registry: ghcr.io/getporter
      shouldPublish: ${{inputs.shouldPublish}}
      skipTests: ${{inputs.skipTests}}
