name: porter/porter-integration
# this will only run when this is on main branch apparently so use pr for now (temporary)
#on:
#  issue_comment:
#    types: [created, edited]
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

env:
  GOVERSION: 1.20.7

jobs:
  Integration_test:
#    if: contains(github.event.comment.body, '/integration_test')
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.6.0
    - uses: actions/setup-go@v4
      with:
        go-version: "${{ env.GOVERSION }}"
    # Unable to determine registry 'ghcr.io/getporter' type. The service connection was not found or the authentication type not supported.
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Native Build
      run: go run mage.go Build
      shell: bash
    - name: Integration Test
      run: go run mage.go -v TestIntegration
      shell: bash
