name: porter/porter-canary
on:
  push:
    branches:
      - main
      - release/*
jobs:
  build_pipelinesrelease_template:
    name: build_pipelinesrelease_template
    uses: ./.github/workflows/build_pipelinesrelease_template.yml
    with:
      registry: ghcr.io/getporter
      shouldPublish: true
      skipTests: false
