# Mark PRs and Issues as stale after a given time. 
# Closes stale issues but not stale PRs.

name: 'Mark stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          days-before-issue-stale: 30  
          days-before-issue-close: 5
          stale-issue-label: 'stale/no-issue-activity'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity.'
          days-before-pr-stale: 1
          days-before-pr-close: -1
          stale-pr-label: 'stale/no-pr-activity'

